language: java
sudo: false
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
jdk:
  - oraclejdk8
notification:
    email: false
# make gradlew accessible
before_install:
 - chmod +x gradlew

#script: "./travis.sh"
