language: java
sudo: false
jdk:
  - oraclejdk8
notification:
    email: false
before_install:
  - chmod a+x ./travis.sh
env:
  global:
    - JAVA_HOME = /usr/lib/jvm/java-8-oracle
script: "./travis.sh"
