language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
notification:
    email: false
#before_install:
#  - chmod a+x ./travis.sh
#script: "./travis.sh"
