name:                webplep
version:             0.1.0.0
github:              "deltadak/plep"
license:             BSD3
author:              "Abby Berkers"
maintainer:          ""
copyright:           "2019 Delta Dak"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deltadak/plep#readme>

dependencies:
  - base >= 4.7 && < 5
  - Spock >= 0.11
  - wai-middleware-static
  - http-types
  - text
  - mtl
  - lucid
  - Spock-lucid
  - monad-logger
  - persistent
  - persistent-sqlite
  - persistent-template

default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - MultiParamTypeClasses
  - OverloadedStrings
  - TypeFamilies

library:
  source-dirs: src

executables:
  webplep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - webplep

tests:
  webplep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - webplep
